### PR TITLE
- add concurrent post unmarshal feature

### PR DESCRIPTION
**Pull request by rocketlaunchr-cto**
requires testing @propersam

### CODE REVIEW

**Review by propersam — APPROVED** [review]
wow...Works just fine andI think this addition kind of improved the speed of dbq when i rerun my benchmark test on the dbq-blog code that queries single row and 100,000+ multiple rows ....my system only have 2 core processors...I think it would be way faster that this on systems with more core processors.

**Comment by propersam** [comment]
Benchmark test on the current master branch..ran twice...

update: 
removed picture showing benchmark

**Comment by propersam** [comment]
Benchmark test on this new branch.. 

update: remove picture showing benchmark

**Comment by rocketlaunchr-cto** [comment]
Something is wrong in your tests.
This PR doesn't increase general performance. It is purely about this: https://godoc.org/github.com/rocketlaunchr/dbq#PostUnmarshaler (adding this method to a struct pointer to change the struct value)

**Comment by propersam** [comment]
> Something is wrong in your tests.
> This PR doesn't increase general performance. It is purely about this: https://godoc.org/github.com/rocketlaunchr/dbq#PostUnmarshaler (adding this method to a struct pointer to change the struct value)

My code for my benchmark test is okay..u can check it out in my [dbq-blog repo.](https://github.com/propersam/dbq-blog/blob/master/dbq-blog_test.go). 

I only thought that i noticed little improvement as the time diffrnce in benchmark tests are nt always dsame..nd diffrnt factors cn result in getting diffrnt outputs dats y it's usually run many times before conclusion....

**Comment by propersam** [comment]
I hv ran the test on this branch and it works okay :+1: ... or is there a specific area that needs more testing ?

**Comment by rocketlaunchr-cto** [comment]
Create a struct and add the post unmarshal method (to the pointer of the
struct) and try and modify the struct in concurrent mode and sequential mode

**Comment by propersam** [comment]
I have written the unittest for this...should i push it to the branch?

**Comment by rocketlaunchr-cto** [comment]
Ok

**Pull request merged**
